// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    $('#btn_1').on('click', function() {
      console.log($(this).val());
      console.log($(this).val());
      console.log($('#btn_1').text());
      return console.log($(this).attr('value'));
    });
    $('.btn_2').on('click', function() {
      return console.log($(this).text());
    });
    $('#field_1').on('mouseover', function() {
      return $(this).css('background-color', 'yellow');
    });
    return $('#field_1').on('mouseout', function() {
      return $(this).css('background-color', 'lightgreen');
    });
  });

}).call(this);
